name: BharatOS CI/CD Pipeline

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-iso:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip tpm2-tools sbctl ffmpeg \
          libopencv-dev libx11-dev jq cubic

    - name: Install Python dependencies
      run: pip install mediapipe opencv-python vosk indic-nlp-library

    - name: Setup Security
      env:
        TAILSCALE_KEY: ${{ secrets.TOKEN }}
        TPM_SECRET: ${{ secrets.TOKEN }}
      run: |
        sudo tailscale up --authkey=$TAILSCALE_KEY
        sudo tpm2_changeauth -o owner:$TPM_SECRET

    - name: Build ISO
      run: |
        cubic_dir="bharatos-build-$(date +%s)"
        mkdir $cubic_dir
        cubic --script scripts/install.sh $cubic_dir
        mv $cubic_dir/*.iso BharatOS-AbhishekAgrahari.iso

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bharatos-iso
        path: BharatOS-AbhishekAgrahari.iso

    - name: Publish Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: BharatOS-AbhishekAgrahari.iso
